import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
	safeArea: {
		flex: 1,
		backgroundColor: '#E8EDF5',
	},
	screenBackdrop: {
		...StyleSheet.absoluteFillObject,
	},
	backgroundOrb: {
		position: 'absolute',
		borderRadius: 999,
		opacity: 0.55,
	},
	backgroundOrbTop: {
		top: -80,
		right: -40,
		width: 260,
		height: 260,
		backgroundColor: '#CFD9FF',
	},
	backgroundOrbMiddle: {
		top: 260,
		left: -60,
		width: 200,
		height: 200,
		backgroundColor: '#D9EFF3',
	},
	backgroundOrbBottom: {
		bottom: -100,
		right: 80,
		width: 240,
		height: 240,
		backgroundColor: '#E0DBFF',
	},
	loginShell: {
		flex: 1,
		justifyContent: 'center',
		padding: 24,
	},
	restoreShell: {
		flex: 1,
	},
	loginPanel: {
		width: '100%',
		maxWidth: 1280,
		flexDirection: 'row',
		justifyContent: 'flex-end',
		alignItems: 'center',
		alignSelf: 'center',
	},
	loginCard: {
		width: '100%',
		maxWidth: 430,
		borderRadius: 28,
		padding: 24,
		backgroundColor: 'rgba(248, 251, 255, 0.86)',
		borderWidth: 1,
		borderColor: 'rgba(255,255,255,0.78)',
		shadowColor: '#7B879B',
		shadowOpacity: 0.18,
		shadowRadius: 28,
		shadowOffset: { width: 0, height: 18 },
		elevation: 10,
	},
	loginShowcaseCard: {
		flex: 1,
		minWidth: 360,
		borderRadius: 36,
		padding: 28,
		backgroundColor: 'rgba(26, 36, 58, 0.92)',
		borderWidth: 1,
		borderColor: 'rgba(111, 145, 255, 0.24)',
	},
	eyebrow: {
		color: '#3E63FF',
		fontSize: 13,
		fontWeight: '700',
		letterSpacing: 1.5,
		textTransform: 'uppercase',
	},
	loginTitle: {
		marginTop: 12,
		color: '#13203B',
		fontSize: 28,
		fontWeight: '800',
	},
	loginSubtitle: {
		marginTop: 10,
		marginBottom: 18,
		color: '#5D697D',
		fontSize: 14,
		lineHeight: 20,
	},
	showcaseEyebrow: {
		color: '#9FB0FF',
		fontSize: 12,
		fontWeight: '700',
		letterSpacing: 1.2,
		textTransform: 'uppercase',
	},
	showcaseTitle: {
		marginTop: 12,
		color: '#F8FAFC',
		fontSize: 28,
		fontWeight: '800',
		lineHeight: 36,
	},
	showcaseChartCard: {
		marginTop: 24,
		minHeight: 170,
		borderRadius: 30,
		padding: 24,
		backgroundColor: 'rgba(20, 32, 57, 0.96)',
		justifyContent: 'flex-end',
	},
	showcaseLine: {
		width: '86%',
		height: 4,
		borderRadius: 999,
		backgroundColor: '#69A5FF',
	},
	showcaseLineShort: {
		marginTop: 18,
		width: '62%',
		height: 4,
		borderRadius: 999,
		backgroundColor: '#7CB7FF',
	},
	showcaseLineDot: {
		position: 'absolute',
		right: 64,
		top: 52,
		width: 20,
		height: 20,
		borderRadius: 999,
		backgroundColor: '#4C8DFF',
		borderWidth: 4,
		borderColor: '#C7DCFF',
	},
	showcaseMetricRow: {
		marginTop: 18,
		gap: 12,
	},
	appShell: {
		width: '100%',
		maxWidth: 1280,
		alignSelf: 'center',
		padding: 14,
	},
	appScrollContent: {
		paddingBottom: 32,
	},
	heroHeader: {
		borderRadius: 24,
		padding: 16,
		backgroundColor: 'rgba(248, 251, 255, 0.84)',
		borderWidth: 1,
		borderColor: 'rgba(255,255,255,0.78)',
		flexDirection: 'row',
		justifyContent: 'space-between',
		gap: 12,
	},
	heroMeta: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 12,
	},
	metricsRow: {
		marginTop: 16,
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 12,
	},
	metricCard: {
		minWidth: 190,
		flexGrow: 1,
		borderRadius: 24,
		padding: 18,
		backgroundColor: 'rgba(247, 250, 255, 0.88)',
		borderWidth: 1,
		borderColor: '#DCE5F5',
	},
	metricCardCompact: {
		minWidth: 160,
		borderRadius: 20,
		padding: 16,
		backgroundColor: '#EEF3FF',
	},
	metricLabel: {
		color: '#64748B',
		fontSize: 12,
		fontWeight: '700',
		textTransform: 'uppercase',
		letterSpacing: 0.8,
	},
	metricValue: {
		marginTop: 10,
		color: '#12213C',
		fontSize: 24,
		fontWeight: '800',
	},
	metricValueCompact: {
		marginTop: 8,
		color: '#12213C',
		fontSize: 16,
		fontWeight: '800',
	},
	banner: {
		marginTop: 14,
		borderRadius: 18,
		paddingHorizontal: 16,
		paddingVertical: 14,
	},
	bannerError: { backgroundColor: '#FDE2E2' },
	bannerSuccess: { backgroundColor: '#DCFCE7' },
	bannerInfo: { backgroundColor: '#DBEAFE' },
	bannerText: {
		color: '#22314B',
		fontSize: 14,
		lineHeight: 20,
	},
	contentRow: {
		marginTop: 16,
		flexDirection: 'row',
		gap: 16,
		alignItems: 'flex-start',
	},
	contentRowStacked: {
		flexDirection: 'column',
		gap: 18,
	},
	mainColumn: { flex: 1.2, minWidth: 0 },
	mainColumnFull: { width: '100%', flex: 0 },
	sideColumn: { flex: 0.8, minWidth: 320 },
	sideColumnFull: { width: '100%', minWidth: 0 },
	sideColumnStack: { gap: 16 },
	sessionBanner: {
		borderRadius: 24,
		padding: 16,
		backgroundColor: 'rgba(248, 251, 255, 0.9)',
		borderWidth: 1,
		borderColor: '#DCE5F5',
		flexDirection: 'row',
		flexWrap: 'wrap',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: 12,
	},
	sessionIdentityRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 12,
		flexShrink: 1,
	},
	sessionAvatar: {
		width: 48,
		height: 48,
		borderRadius: 999,
		backgroundColor: '#355CFF',
		alignItems: 'center',
		justifyContent: 'center',
	},
	sessionAvatarText: {
		color: '#F8FAFC',
		fontSize: 16,
		fontWeight: '800',
	},
	sessionIdentityText: {
		flexShrink: 1,
		gap: 4,
	},
	sessionUserName: {
		color: '#13203B',
		fontSize: 17,
		fontWeight: '800',
	},
	sessionUserMeta: {
		color: '#64748B',
		fontSize: 13,
	},
	sectionCard: {
		borderRadius: 24,
		padding: 16,
		backgroundColor: 'rgba(248, 251, 255, 0.84)',
		borderWidth: 1,
		borderColor: '#DCE5F5',
	},
	sectionHeaderRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'flex-start',
		gap: 12,
	},
	sectionHeaderRowStacked: {
		flexDirection: 'column',
	},
	headerActionRow: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 10,
	},
	headerActionRowStacked: {
		width: '100%',
		justifyContent: 'flex-start',
	},
	sectionTitle: {
		color: '#0F1E3D',
		fontSize: 18,
		fontWeight: '800',
	},
	sectionSubtitle: {
		marginTop: 6,
		color: '#64748B',
		fontSize: 13,
		lineHeight: 18,
	},
	toolbarRow: { marginTop: 14, marginBottom: 8 },
	input: {
		borderRadius: 16,
		borderWidth: 1,
		borderColor: '#D7E1F2',
		backgroundColor: 'rgba(255,255,255,0.9)',
		paddingHorizontal: 14,
		paddingVertical: 10,
		color: '#12213C',
		fontSize: 14,
	},
	searchInput: { backgroundColor: 'rgba(255,255,255,0.96)' },
	filterChipRow: { gap: 10, paddingVertical: 6 },
	filterChip: {
		paddingHorizontal: 14,
		paddingVertical: 10,
		borderRadius: 999,
		backgroundColor: '#E8EEFC',
	},
	filterChipActive: { backgroundColor: '#355CFF' },
	filterChipPressed: { opacity: 0.82 },
	filterChipText: { color: '#49566E', fontSize: 13, fontWeight: '700' },
	filterChipTextActive: { color: '#F8FAFC', fontSize: 13, fontWeight: '700' },
	calendarNavRow: {
		marginTop: 12,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: 12,
	},
	calendarMonthTitle: {
		color: '#13203B',
		fontSize: 16,
		fontWeight: '800',
	},
	scheduleDayGrid: {
		marginTop: 14,
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 12,
	},
	scheduleDayGridStacked: {
		flexDirection: 'column',
		flexWrap: 'nowrap',
	},
	mobileScheduleList: {
		marginTop: 14,
		gap: 12,
	},
	mobileScheduleSection: {
		borderRadius: 22,
		padding: 12,
		backgroundColor: 'rgba(255,255,255,0.9)',
		borderWidth: 1,
		borderColor: '#DFE8F6',
	},
	mobileScheduleSectionActive: {
		borderColor: '#355CFF',
		backgroundColor: '#EEF3FF',
	},
	mobileScheduleHeader: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'flex-start',
		gap: 12,
		paddingBottom: 10,
		borderBottomWidth: 1,
		borderBottomColor: '#E3EAF8',
	},
	mobileScheduleScroll: {
		marginTop: 12,
		maxHeight: 320,
	},
	scheduleDayColumn: {
		flex: 1,
		minWidth: 220,
		borderRadius: 22,
		padding: 12,
		backgroundColor: 'rgba(255,255,255,0.9)',
		borderWidth: 1,
		borderColor: '#DFE8F6',
	},
	scheduleDayColumnStacked: {
		width: '100%',
		minWidth: 0,
		flex: 0,
	},
	scheduleDayColumnActive: {
		borderColor: '#355CFF',
		backgroundColor: '#EEF3FF',
	},
	scheduleDayHeader: {
		gap: 4,
		paddingBottom: 10,
		borderBottomWidth: 1,
		borderBottomColor: '#E3EAF8',
	},
	scheduleDayTitle: {
		color: '#13203B',
		fontSize: 17,
		fontWeight: '800',
	},
	scheduleDayDate: {
		color: '#526178',
		fontSize: 13,
	},
	scheduleDayCount: {
		color: '#355CFF',
		fontSize: 12,
		fontWeight: '800',
		textTransform: 'uppercase',
	},
	scheduleDayScroll: {
		marginTop: 12,
		maxHeight: 420,
	},
	scheduleDayScrollCompact: {
		marginTop: 12,
		maxHeight: 280,
	},
	scheduleDayStack: {
		gap: 10,
		paddingBottom: 4,
	},
	scheduleDayEmpty: {
		paddingVertical: 18,
	},
	calendarWeekHeaderRow: {
		marginTop: 16,
		flexDirection: 'row',
		justifyContent: 'space-between',
		gap: 8,
	},
	calendarWeekHeaderText: {
		flex: 1,
		textAlign: 'center',
		color: '#64748B',
		fontSize: 12,
		fontWeight: '700',
	},
	calendarGrid: {
		marginTop: 12,
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 8,
	},
	calendarCell: {
		width: '13.2%',
		minWidth: 110,
		flexGrow: 1,
		minHeight: 102,
		borderRadius: 22,
		padding: 12,
		backgroundColor: 'rgba(255,255,255,0.9)',
		borderWidth: 1,
		borderColor: '#DFE8F6',
	},
	calendarCellMuted: { opacity: 0.58 },
	calendarCellActive: { backgroundColor: '#EAF0FF', borderColor: '#355CFF' },
	calendarCellPressed: { opacity: 0.88 },
	calendarCellText: { color: '#13203B', fontSize: 14, fontWeight: '800' },
	calendarCellTextActive: { color: '#355CFF', fontSize: 14, fontWeight: '800' },
	calendarItemPreview: { marginTop: 6, color: '#5B677A', fontSize: 11 },
	calendarMoreText: { marginTop: 6, color: '#355CFF', fontSize: 11, fontWeight: '700' },
	selectedDateHeader: { marginTop: 18 },
	loadingState: { alignItems: 'center', justifyContent: 'center', paddingVertical: 28, gap: 10 },
	loadingText: { color: '#64748B', fontSize: 13 },
	cardStack: { marginTop: 14, gap: 12 },
	visitPlanCard: {
		borderRadius: 24,
		padding: 16,
		backgroundColor: 'rgba(255,255,255,0.92)',
		borderWidth: 1,
		borderColor: '#DDE7F6',
	},
	visitPlanCardCompact: {
		borderRadius: 18,
		padding: 12,
		backgroundColor: 'rgba(255,255,255,0.94)',
		borderWidth: 1,
		borderColor: '#DDE7F6',
	},
	visitPlanCardHeader: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
	visitPlanCardTitleWrap: { flex: 1 },
	visitPlanCardTitle: { color: '#13203B', fontSize: 17, fontWeight: '800' },
	visitPlanCardBadge: { color: '#355CFF', fontSize: 12, fontWeight: '800', textTransform: 'uppercase' },
	visitPlanCardMeta: { marginTop: 6, color: '#64748B', fontSize: 13 },
	inlineButtonRow: { marginTop: 12, flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
	inlineButtonRowCompact: { marginTop: 10, flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
	primaryButton: {
		minHeight: 48,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 18,
		backgroundColor: '#355CFF',
		paddingHorizontal: 20,
	},
	primaryButtonSmall: {
		minHeight: 42,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 16,
		backgroundColor: '#355CFF',
		paddingHorizontal: 18,
	},
	primaryButtonPressed: { opacity: 0.88 },
	primaryButtonText: { color: '#F8FAFC', fontSize: 14, fontWeight: '800' },
	secondaryButton: {
		minHeight: 42,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 16,
		backgroundColor: '#E7EEFF',
		paddingHorizontal: 18,
	},
	secondaryButtonMuted: {
		minHeight: 42,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 16,
		backgroundColor: '#E7EEFF',
		paddingHorizontal: 18,
	},
	secondaryButtonMutedCompact: {
		minHeight: 34,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 12,
		backgroundColor: '#E7EEFF',
		paddingHorizontal: 12,
	},
	secondaryButtonText: { color: '#2643B8', fontSize: 13, fontWeight: '800' },
	inlineActionButton: { marginTop: 12 },
	buttonDisabled: { opacity: 0.6 },
	emptyState: { paddingVertical: 24, gap: 8 },
	emptyStateTitle: { color: '#13203B', fontSize: 18, fontWeight: '700' },
	emptyStateDescription: { color: '#64748B', fontSize: 14, lineHeight: 20 },
	fieldBlock: { gap: 8 },
	fieldLabel: { color: '#334155', fontSize: 13, fontWeight: '700' },
	fieldHelper: { color: '#64748B', fontSize: 12, lineHeight: 17 },
	multilineInput: { minHeight: 110, textAlignVertical: 'top' },
	meetingResultInput: { minHeight: 140 },
	lookupInput: { paddingRight: 18 },
	lookupSelectionRow: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 12,
		alignItems: 'center',
		borderRadius: 14,
		paddingHorizontal: 14,
		paddingVertical: 9,
		backgroundColor: '#EEF3FF',
	},
	lookupSelectionCaption: { color: '#64748B', fontSize: 11, fontWeight: '800', textTransform: 'uppercase' },
	lookupSelectionLabel: { flexShrink: 1, color: '#2643B8', fontSize: 13, fontWeight: '700' },
	clearSelectionButton: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, backgroundColor: '#DDE7FF' },
	clearSelectionText: { color: '#2643B8', fontSize: 12, fontWeight: '800' },
	lookupPanel: {
		borderRadius: 16,
		backgroundColor: 'rgba(255,255,255,0.92)',
		borderWidth: 1,
		borderColor: '#D7E1F2',
		overflow: 'hidden',
	},
	lookupScroll: { maxHeight: 132 },
	lookupHint: { paddingHorizontal: 14, paddingVertical: 12, color: '#64748B', fontSize: 13 },
	lookupOption: { paddingHorizontal: 14, paddingVertical: 12, borderTopWidth: 1, borderTopColor: '#E7EEF8' },
	lookupOptionActive: { backgroundColor: '#EEF3FF' },
	lookupOptionPressed: { opacity: 0.85 },
	lookupOptionText: { color: '#13203B', fontSize: 14, fontWeight: '700' },
	lookupOptionSubtext: { marginTop: 4, color: '#64748B', fontSize: 12 },
	selectionChipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
	selectionChip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, backgroundColor: '#E8EEFC' },
	selectionChipStatic: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, backgroundColor: '#EEF3FF' },
	selectionChipText: { color: '#2643B8', fontSize: 12, fontWeight: '800' },
	rowFields: { flexDirection: 'row', gap: 12 },
	halfField: { flex: 1 },
	segmentedRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
	segmentOption: { paddingHorizontal: 12, paddingVertical: 10, borderRadius: 999, backgroundColor: '#E8EEFC' },
	segmentOptionActive: { backgroundColor: '#355CFF' },
	segmentOptionPressed: { opacity: 0.82 },
	segmentOptionText: { color: '#475569', fontSize: 13, fontWeight: '700' },
	segmentOptionTextActive: { color: '#F8FAFC', fontSize: 13, fontWeight: '700' },
	detailTitle: { marginTop: 10, color: '#13203B', fontSize: 24, fontWeight: '800' },
	detailMeta: { color: '#64748B', fontSize: 13, marginTop: 6 },
	detailSectionCard: { marginTop: 12, borderRadius: 22, padding: 16, backgroundColor: '#F5F8FF', borderWidth: 1, borderColor: '#E3EAF8' },
	detailSectionTitle: { color: '#2643B8', fontSize: 14, fontWeight: '800', marginBottom: 8 },
	detailBody: { color: '#1E293B', fontSize: 15, lineHeight: 22 },
	detailBodyMuted: { color: '#5B6474', fontSize: 14, lineHeight: 20 },
	summaryStatsGrid: { marginTop: 12, gap: 10 },
	summaryStatCard: {
		borderRadius: 18,
		padding: 14,
		backgroundColor: '#F5F8FF',
		borderWidth: 1,
		borderColor: '#E3EAF8',
	},
	summaryStatLabel: {
		color: '#64748B',
		fontSize: 11,
		fontWeight: '800',
		textTransform: 'uppercase',
	},
	summaryStatValue: {
		marginTop: 8,
		color: '#13203B',
		fontSize: 24,
		fontWeight: '800',
	},
	summaryStatValueSmall: {
		marginTop: 8,
		color: '#13203B',
		fontSize: 15,
		fontWeight: '800',
	},
	summaryListScroll: {
		marginTop: 14,
		maxHeight: 420,
	},
	summaryListStack: {
		gap: 10,
		paddingBottom: 2,
	},
	summaryListCard: {
		borderRadius: 18,
		padding: 14,
		backgroundColor: '#F5F8FF',
		borderWidth: 1,
		borderColor: '#E3EAF8',
	},
	statusUpdateRow: { gap: 8 },
	statusAction: { borderRadius: 16, backgroundColor: '#E8EEFC', paddingHorizontal: 14, paddingVertical: 12 },
	statusActionActive: { backgroundColor: '#355CFF' },
	statusActionPressed: { opacity: 0.85 },
	statusActionText: { color: '#13203B', fontSize: 13, fontWeight: '700' },
	statusActionTextActive: { color: '#F8FAFC', fontSize: 13, fontWeight: '700' },
	modalBackdrop: {
		flex: 1,
		backgroundColor: 'rgba(15, 23, 42, 0.34)',
		padding: 20,
		justifyContent: 'center',
	},
	modalCard: {
		width: '100%',
		maxWidth: 1120,
		maxHeight: '92%',
		alignSelf: 'center',
		borderRadius: 32,
		padding: 22,
		backgroundColor: '#F8FBFF',
		borderWidth: 1,
		borderColor: '#E1E8F6',
	},
	modalScrollContent: { gap: 16, paddingTop: 16, paddingBottom: 16 },
	modalFooterRow: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 16 },
	formHeroStrip: { borderRadius: 22, padding: 16, backgroundColor: '#E9EEFF' },
	formHeroTitle: { color: '#2643B8', fontSize: 16, fontWeight: '800' },
	formHeroText: { marginTop: 6, color: '#56657A', fontSize: 13, lineHeight: 18 },
	datePickerCard: { borderRadius: 20, padding: 12, backgroundColor: '#F5F8FF', borderWidth: 1, borderColor: '#E3EAF8' },
	modalCalendarMonthTitle: {
		marginTop: 8,
		color: '#13203B',
		fontSize: 15,
		fontWeight: '800',
	},
	modalCalendarWeekHeaderRow: {
		marginTop: 10,
		flexDirection: 'row',
		justifyContent: 'space-between',
		gap: 4,
	},
	modalCalendarWeekHeaderText: {
		flex: 1,
		textAlign: 'center',
		color: '#64748B',
		fontSize: 10,
		fontWeight: '700',
	},
	modalCalendarGrid: {
		marginTop: 8,
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 4,
	},
	modalCalendarCell: {
		width: '13.4%',
		minWidth: 40,
		flexGrow: 1,
		minHeight: 40,
		borderRadius: 12,
		paddingVertical: 8,
		paddingHorizontal: 4,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: 'rgba(255,255,255,0.94)',
		borderWidth: 1,
		borderColor: '#DFE8F6',
	},
	modalCalendarCellMuted: { opacity: 0.5 },
	modalCalendarCellActive: { backgroundColor: '#EAF0FF', borderColor: '#355CFF' },
	modalCalendarCellPressed: { opacity: 0.88 },
	modalCalendarCellText: { color: '#13203B', fontSize: 12, fontWeight: '700' },
	modalCalendarCellTextActive: { color: '#355CFF', fontSize: 12, fontWeight: '800' },
	timePickerGrid: { marginTop: 8, flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
	timeChip: { paddingHorizontal: 10, paddingVertical: 8, borderRadius: 999, backgroundColor: '#E8EEFC' },
	timeChipActive: { backgroundColor: '#355CFF' },
	timeChipText: { color: '#475569', fontSize: 12, fontWeight: '700' },
	timeChipTextActive: { color: '#F8FAFC', fontSize: 12, fontWeight: '700' },
	workspaceHeaderCard: {
		borderRadius: 28,
		padding: 20,
		backgroundColor: 'rgba(248, 251, 255, 0.88)',
		borderWidth: 1,
		borderColor: '#DCE5F5',
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		gap: 16,
		flexWrap: 'wrap',
	},
	workspaceHeaderTextWrap: {
		flex: 1,
		minWidth: 240,
	},
	workspaceHeaderTitle: {
		marginTop: 10,
		color: '#13203B',
		fontSize: 28,
		fontWeight: '800',
	},
	workspaceHeaderSubtitle: {
		marginTop: 8,
		color: '#5D697D',
		fontSize: 14,
		lineHeight: 20,
	},
	workspaceHeaderActions: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 12,
		flexWrap: 'wrap',
		justifyContent: 'flex-end',
	},
	workspaceIdentityBadge: {
		borderRadius: 18,
		paddingHorizontal: 14,
		paddingVertical: 12,
		backgroundColor: '#EEF3FF',
		minWidth: 180,
	},
	workspaceIdentityName: {
		color: '#13203B',
		fontSize: 14,
		fontWeight: '800',
	},
	workspaceIdentityMeta: {
		marginTop: 4,
		color: '#64748B',
		fontSize: 12,
	},
	pageStack: {
		marginTop: 16,
		gap: 16,
	},
	pageHeaderCard: {
		borderRadius: 24,
		padding: 16,
		backgroundColor: 'rgba(248, 251, 255, 0.84)',
		borderWidth: 1,
		borderColor: '#DCE5F5',
	},
	pageTitle: {
		color: '#13203B',
		fontSize: 22,
		fontWeight: '800',
	},
	pageSubtitle: {
		marginTop: 8,
		color: '#64748B',
		fontSize: 14,
		lineHeight: 20,
	},
	reviewMetricGrid: {
		flexDirection: 'row',
		gap: 12,
		flexWrap: 'wrap',
	},
	clientWorkspaceLayout: {
		flexDirection: 'row',
		gap: 16,
		alignItems: 'flex-start',
		flexWrap: 'wrap',
	},
	clientDirectoryColumn: {
		width: 320,
		maxWidth: '100%',
		flexGrow: 1,
	},
	clientDetailColumn: {
		flex: 1,
		minWidth: 320,
		gap: 16,
	},
	clientDirectoryShell: {
		width: '100%',
		maxWidth: 720,
	},
	clientDetailHeaderRow: {
		flexDirection: 'row',
		justifyContent: 'flex-start',
		alignItems: 'center',
		gap: 10,
	},
	clientSearchInput: {
		marginTop: 14,
	},
	clientListScroll: {
		marginTop: 14,
		maxHeight: 640,
	},
	clientListStack: {
		gap: 10,
		paddingBottom: 2,
	},
	clientListCard: {
		borderRadius: 18,
		padding: 14,
		backgroundColor: '#F5F8FF',
		borderWidth: 1,
		borderColor: '#E3EAF8',
	},
	clientListCardActive: {
		borderColor: '#355CFF',
		backgroundColor: '#EEF3FF',
	},
	clientListTitle: {
		color: '#13203B',
		fontSize: 15,
		fontWeight: '800',
	},
	clientListMeta: {
		marginTop: 6,
		color: '#64748B',
		fontSize: 12,
	},
	clientListMetricsRow: {
		marginTop: 10,
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 8,
	},
	clientListMetric: {
		paddingHorizontal: 10,
		paddingVertical: 6,
		borderRadius: 999,
		backgroundColor: '#E8EEFC',
		color: '#2643B8',
		fontSize: 11,
		fontWeight: '800',
	},
	clientSummaryGrid: {
		marginTop: 14,
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 10,
	},
	workspaceTabButton: {
		paddingHorizontal: 14,
		paddingVertical: 10,
		borderRadius: 999,
		backgroundColor: '#E8EEFC',
	},
	workspaceTabButtonActive: {
		backgroundColor: '#355CFF',
	},
	workspaceTabButtonText: {
		color: '#49566E',
		fontSize: 13,
		fontWeight: '700',
	},
	workspaceTabButtonTextActive: {
		color: '#F8FAFC',
		fontSize: 13,
		fontWeight: '700',
	},
	clientDetailsStack: {
		gap: 12,
	},
	entityListStack: {
		gap: 10,
	},
	bottomNavShell: {
		paddingHorizontal: 16,
		paddingTop: 8,
		paddingBottom: 18,
		backgroundColor: 'transparent',
	},
	bottomNavCard: {
		maxWidth: 720,
		width: '100%',
		alignSelf: 'center',
		borderRadius: 24,
		padding: 8,
		backgroundColor: 'rgba(248, 251, 255, 0.96)',
		borderWidth: 1,
		borderColor: '#DCE5F5',
		flexDirection: 'row',
		gap: 8,
	},
	bottomNavButton: {
		flex: 1,
		minHeight: 52,
		borderRadius: 18,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#EEF3FF',
	},
	bottomNavButtonActive: {
		backgroundColor: '#355CFF',
	},
	bottomNavButtonPressed: {
		opacity: 0.84,
	},
	bottomNavButtonText: {
		color: '#2643B8',
		fontSize: 13,
		fontWeight: '800',
	},
	bottomNavButtonTextActive: {
		color: '#F8FAFC',
		fontSize: 13,
		fontWeight: '800',
	},
});