import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
	safeArea: {
		flex: 1,
		backgroundColor: '#E8EDF5',
	},
	screenBackdrop: {
		...StyleSheet.absoluteFillObject,
	},
	backgroundOrb: {
		position: 'absolute',
		borderRadius: 999,
		opacity: 0.55,
	},
	backgroundOrbTop: {
		top: -80,
		right: -40,
		width: 260,
		height: 260,
		backgroundColor: '#CFD9FF',
	},
	backgroundOrbMiddle: {
		top: 260,
		left: -60,
		width: 200,
		height: 200,
		backgroundColor: '#D9EFF3',
	},
	backgroundOrbBottom: {
		bottom: -100,
		right: 80,
		width: 240,
		height: 240,
		backgroundColor: '#E0DBFF',
	},
	loginShell: {
		flex: 1,
		justifyContent: 'center',
		padding: 24,
	},
	loginPanel: {
		width: '100%',
		maxWidth: 1280,
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 24,
		alignSelf: 'center',
	},
	loginCard: {
		flex: 1,
		minWidth: 340,
		borderRadius: 36,
		padding: 30,
		backgroundColor: 'rgba(248, 251, 255, 0.86)',
		borderWidth: 1,
		borderColor: 'rgba(255,255,255,0.78)',
		shadowColor: '#7B879B',
		shadowOpacity: 0.18,
		shadowRadius: 28,
		shadowOffset: { width: 0, height: 18 },
		elevation: 10,
	},
	loginShowcaseCard: {
		flex: 1,
		minWidth: 360,
		borderRadius: 36,
		padding: 28,
		backgroundColor: 'rgba(26, 36, 58, 0.92)',
		borderWidth: 1,
		borderColor: 'rgba(111, 145, 255, 0.24)',
	},
	eyebrow: {
		color: '#3E63FF',
		fontSize: 13,
		fontWeight: '700',
		letterSpacing: 1.5,
		textTransform: 'uppercase',
	},
	loginTitle: {
		marginTop: 12,
		color: '#13203B',
		fontSize: 32,
		fontWeight: '800',
	},
	loginSubtitle: {
		marginTop: 10,
		marginBottom: 24,
		color: '#5D697D',
		fontSize: 15,
		lineHeight: 22,
	},
	showcaseEyebrow: {
		color: '#9FB0FF',
		fontSize: 12,
		fontWeight: '700',
		letterSpacing: 1.2,
		textTransform: 'uppercase',
	},
	showcaseTitle: {
		marginTop: 12,
		color: '#F8FAFC',
		fontSize: 28,
		fontWeight: '800',
		lineHeight: 36,
	},
	showcaseChartCard: {
		marginTop: 24,
		minHeight: 170,
		borderRadius: 30,
		padding: 24,
		backgroundColor: 'rgba(20, 32, 57, 0.96)',
		justifyContent: 'flex-end',
	},
	showcaseLine: {
		width: '86%',
		height: 4,
		borderRadius: 999,
		backgroundColor: '#69A5FF',
	},
	showcaseLineShort: {
		marginTop: 18,
		width: '62%',
		height: 4,
		borderRadius: 999,
		backgroundColor: '#7CB7FF',
	},
	showcaseLineDot: {
		position: 'absolute',
		right: 64,
		top: 52,
		width: 20,
		height: 20,
		borderRadius: 999,
		backgroundColor: '#4C8DFF',
		borderWidth: 4,
		borderColor: '#C7DCFF',
	},
	showcaseMetricRow: {
		marginTop: 18,
		gap: 12,
	},
	appShell: {
		flex: 1,
		padding: 18,
	},
	heroHeader: {
		borderRadius: 30,
		padding: 22,
		backgroundColor: 'rgba(248, 251, 255, 0.84)',
		borderWidth: 1,
		borderColor: 'rgba(255,255,255,0.78)',
		flexDirection: 'row',
		justifyContent: 'space-between',
		gap: 12,
	},
	heroMeta: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 12,
	},
	metricsRow: {
		marginTop: 16,
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 12,
	},
	metricCard: {
		minWidth: 190,
		flexGrow: 1,
		borderRadius: 24,
		padding: 18,
		backgroundColor: 'rgba(247, 250, 255, 0.88)',
		borderWidth: 1,
		borderColor: '#DCE5F5',
	},
	metricCardCompact: {
		minWidth: 160,
		borderRadius: 20,
		padding: 16,
		backgroundColor: '#EEF3FF',
	},
	metricLabel: {
		color: '#64748B',
		fontSize: 12,
		fontWeight: '700',
		textTransform: 'uppercase',
		letterSpacing: 0.8,
	},
	metricValue: {
		marginTop: 10,
		color: '#12213C',
		fontSize: 24,
		fontWeight: '800',
	},
	metricValueCompact: {
		marginTop: 8,
		color: '#12213C',
		fontSize: 16,
		fontWeight: '800',
	},
	banner: {
		marginTop: 14,
		borderRadius: 18,
		paddingHorizontal: 16,
		paddingVertical: 14,
	},
	bannerError: { backgroundColor: '#FDE2E2' },
	bannerSuccess: { backgroundColor: '#DCFCE7' },
	bannerInfo: { backgroundColor: '#DBEAFE' },
	bannerText: {
		color: '#22314B',
		fontSize: 14,
		lineHeight: 20,
	},
	contentRow: {
		flex: 1,
		marginTop: 16,
		flexDirection: 'row',
		gap: 16,
	},
	mainColumn: { flex: 1.25 },
	sideColumn: { flex: 0.85 },
	sideColumnStack: { gap: 16, paddingBottom: 40 },
	sectionCard: {
		borderRadius: 28,
		padding: 18,
		backgroundColor: 'rgba(248, 251, 255, 0.84)',
		borderWidth: 1,
		borderColor: '#DCE5F5',
	},
	sectionHeaderRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'flex-start',
		gap: 12,
	},
	headerActionRow: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 10,
	},
	sectionTitle: {
		color: '#0F1E3D',
		fontSize: 22,
		fontWeight: '800',
	},
	sectionSubtitle: {
		marginTop: 6,
		color: '#64748B',
		fontSize: 13,
		lineHeight: 18,
	},
	toolbarRow: { marginTop: 16, marginBottom: 10 },
	input: {
		borderRadius: 18,
		borderWidth: 1,
		borderColor: '#D7E1F2',
		backgroundColor: 'rgba(255,255,255,0.9)',
		paddingHorizontal: 14,
		paddingVertical: 12,
		color: '#12213C',
		fontSize: 15,
	},
	searchInput: { backgroundColor: 'rgba(255,255,255,0.96)' },
	filterChipRow: { gap: 10, paddingVertical: 6 },
	filterChip: {
		paddingHorizontal: 14,
		paddingVertical: 10,
		borderRadius: 999,
		backgroundColor: '#E8EEFC',
	},
	filterChipActive: { backgroundColor: '#355CFF' },
	filterChipPressed: { opacity: 0.82 },
	filterChipText: { color: '#49566E', fontSize: 13, fontWeight: '700' },
	filterChipTextActive: { color: '#F8FAFC', fontSize: 13, fontWeight: '700' },
	calendarNavRow: {
		marginTop: 12,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: 12,
	},
	calendarMonthTitle: {
		color: '#13203B',
		fontSize: 18,
		fontWeight: '800',
	},
	calendarWeekHeaderRow: {
		marginTop: 16,
		flexDirection: 'row',
		justifyContent: 'space-between',
		gap: 8,
	},
	calendarWeekHeaderText: {
		flex: 1,
		textAlign: 'center',
		color: '#64748B',
		fontSize: 12,
		fontWeight: '700',
	},
	calendarGrid: {
		marginTop: 12,
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 8,
	},
	calendarCell: {
		width: '13.2%',
		minWidth: 110,
		flexGrow: 1,
		minHeight: 102,
		borderRadius: 22,
		padding: 12,
		backgroundColor: 'rgba(255,255,255,0.9)',
		borderWidth: 1,
		borderColor: '#DFE8F6',
	},
	calendarCellMuted: { opacity: 0.58 },
	calendarCellActive: { backgroundColor: '#EAF0FF', borderColor: '#355CFF' },
	calendarCellPressed: { opacity: 0.88 },
	calendarCellText: { color: '#13203B', fontSize: 14, fontWeight: '800' },
	calendarCellTextActive: { color: '#355CFF', fontSize: 14, fontWeight: '800' },
	calendarItemPreview: { marginTop: 6, color: '#5B677A', fontSize: 11 },
	calendarMoreText: { marginTop: 6, color: '#355CFF', fontSize: 11, fontWeight: '700' },
	selectedDateHeader: { marginTop: 18 },
	loadingState: { alignItems: 'center', justifyContent: 'center', paddingVertical: 28, gap: 10 },
	loadingText: { color: '#64748B', fontSize: 13 },
	cardStack: { marginTop: 14, gap: 12 },
	visitPlanCard: {
		borderRadius: 24,
		padding: 16,
		backgroundColor: 'rgba(255,255,255,0.92)',
		borderWidth: 1,
		borderColor: '#DDE7F6',
	},
	visitPlanCardHeader: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
	visitPlanCardTitleWrap: { flex: 1 },
	visitPlanCardTitle: { color: '#13203B', fontSize: 17, fontWeight: '800' },
	visitPlanCardBadge: { color: '#355CFF', fontSize: 12, fontWeight: '800', textTransform: 'uppercase' },
	visitPlanCardMeta: { marginTop: 6, color: '#64748B', fontSize: 13 },
	inlineButtonRow: { marginTop: 12, flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
	primaryButton: {
		minHeight: 48,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 18,
		backgroundColor: '#355CFF',
		paddingHorizontal: 20,
	},
	primaryButtonSmall: {
		minHeight: 42,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 16,
		backgroundColor: '#355CFF',
		paddingHorizontal: 18,
	},
	primaryButtonPressed: { opacity: 0.88 },
	primaryButtonText: { color: '#F8FAFC', fontSize: 14, fontWeight: '800' },
	secondaryButton: {
		minHeight: 42,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 16,
		backgroundColor: '#E7EEFF',
		paddingHorizontal: 18,
	},
	secondaryButtonMuted: {
		minHeight: 42,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 16,
		backgroundColor: '#E7EEFF',
		paddingHorizontal: 18,
	},
	secondaryButtonText: { color: '#2643B8', fontSize: 13, fontWeight: '800' },
	inlineActionButton: { marginTop: 12 },
	buttonDisabled: { opacity: 0.6 },
	emptyState: { paddingVertical: 24, gap: 8 },
	emptyStateTitle: { color: '#13203B', fontSize: 18, fontWeight: '700' },
	emptyStateDescription: { color: '#64748B', fontSize: 14, lineHeight: 20 },
	fieldBlock: { gap: 8 },
	fieldLabel: { color: '#334155', fontSize: 13, fontWeight: '700' },
	fieldHelper: { color: '#64748B', fontSize: 12, lineHeight: 17 },
	multilineInput: { minHeight: 110, textAlignVertical: 'top' },
	meetingResultInput: { minHeight: 140 },
	lookupTitleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
	lookupMetaText: { color: '#64748B', fontSize: 11, fontWeight: '700', textTransform: 'uppercase' },
	lookupInput: { paddingRight: 18 },
	lookupSelectionRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		gap: 12,
		alignItems: 'center',
		borderRadius: 16,
		paddingHorizontal: 14,
		paddingVertical: 10,
		backgroundColor: '#EEF3FF',
	},
	lookupSelectionLabel: { flex: 1, color: '#2643B8', fontSize: 13, fontWeight: '700' },
	clearSelectionButton: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, backgroundColor: '#DDE7FF' },
	clearSelectionText: { color: '#2643B8', fontSize: 12, fontWeight: '800' },
	lookupPanel: {
		borderRadius: 20,
		backgroundColor: 'rgba(255,255,255,0.92)',
		borderWidth: 1,
		borderColor: '#D7E1F2',
		overflow: 'hidden',
	},
	lookupScroll: { maxHeight: 190 },
	lookupHint: { paddingHorizontal: 14, paddingVertical: 12, color: '#64748B', fontSize: 13 },
	lookupOption: { paddingHorizontal: 14, paddingVertical: 12, borderTopWidth: 1, borderTopColor: '#E7EEF8' },
	lookupOptionActive: { backgroundColor: '#EEF3FF' },
	lookupOptionPressed: { opacity: 0.85 },
	lookupOptionText: { color: '#13203B', fontSize: 14, fontWeight: '700' },
	lookupOptionSubtext: { marginTop: 4, color: '#64748B', fontSize: 12 },
	selectionChipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
	selectionChip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, backgroundColor: '#E8EEFC' },
	selectionChipStatic: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, backgroundColor: '#EEF3FF' },
	selectionChipText: { color: '#2643B8', fontSize: 12, fontWeight: '800' },
	rowFields: { flexDirection: 'row', gap: 12 },
	halfField: { flex: 1 },
	segmentedRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
	segmentOption: { paddingHorizontal: 12, paddingVertical: 10, borderRadius: 999, backgroundColor: '#E8EEFC' },
	segmentOptionActive: { backgroundColor: '#355CFF' },
	segmentOptionPressed: { opacity: 0.82 },
	segmentOptionText: { color: '#475569', fontSize: 13, fontWeight: '700' },
	segmentOptionTextActive: { color: '#F8FAFC', fontSize: 13, fontWeight: '700' },
	detailTitle: { marginTop: 10, color: '#13203B', fontSize: 24, fontWeight: '800' },
	detailMeta: { color: '#64748B', fontSize: 13, marginTop: 6 },
	detailSectionCard: { marginTop: 12, borderRadius: 22, padding: 16, backgroundColor: '#F5F8FF', borderWidth: 1, borderColor: '#E3EAF8' },
	detailSectionTitle: { color: '#2643B8', fontSize: 14, fontWeight: '800', marginBottom: 8 },
	detailBody: { color: '#1E293B', fontSize: 15, lineHeight: 22 },
	detailBodyMuted: { color: '#5B6474', fontSize: 14, lineHeight: 20 },
	statusUpdateRow: { gap: 8 },
	statusAction: { borderRadius: 16, backgroundColor: '#E8EEFC', paddingHorizontal: 14, paddingVertical: 12 },
	statusActionActive: { backgroundColor: '#355CFF' },
	statusActionPressed: { opacity: 0.85 },
	statusActionText: { color: '#13203B', fontSize: 13, fontWeight: '700' },
	statusActionTextActive: { color: '#F8FAFC', fontSize: 13, fontWeight: '700' },
	modalBackdrop: {
		flex: 1,
		backgroundColor: 'rgba(15, 23, 42, 0.34)',
		padding: 20,
		justifyContent: 'center',
	},
	modalCard: {
		width: '100%',
		maxWidth: 1120,
		maxHeight: '92%',
		alignSelf: 'center',
		borderRadius: 32,
		padding: 22,
		backgroundColor: '#F8FBFF',
		borderWidth: 1,
		borderColor: '#E1E8F6',
	},
	modalScrollContent: { gap: 16, paddingTop: 16, paddingBottom: 16 },
	modalFooterRow: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 16 },
	formHeroStrip: { borderRadius: 22, padding: 16, backgroundColor: '#E9EEFF' },
	formHeroTitle: { color: '#2643B8', fontSize: 16, fontWeight: '800' },
	formHeroText: { marginTop: 6, color: '#56657A', fontSize: 13, lineHeight: 18 },
	datePickerCard: { borderRadius: 24, padding: 16, backgroundColor: '#F5F8FF', borderWidth: 1, borderColor: '#E3EAF8' },
	timePickerGrid: { marginTop: 8, flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
	timeChip: { paddingHorizontal: 10, paddingVertical: 8, borderRadius: 999, backgroundColor: '#E8EEFC' },
	timeChipActive: { backgroundColor: '#355CFF' },
	timeChipText: { color: '#475569', fontSize: 12, fontWeight: '700' },
	timeChipTextActive: { color: '#F8FAFC', fontSize: 12, fontWeight: '700' },
});